---
- name: Update packages
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
    upgrade: safe
    autoremove: true

- name: Install packages
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
